//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Training.SuperAdmin
{
    public partial class CreateUser
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtLoginID;
        protected global::System.Web.UI.WebControls.DropDownList ddlRole;
        protected global::System.Web.UI.WebControls.TextBox txtCorrespondingID;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.DropDownList ddlActive;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Button btnClear;
    }
}