//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace Training.Trainee
{
    public partial class DashboardDetails
    {
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.Label lblSummary;
        protected global::System.Web.UI.WebControls.GridView gvDetails;
    }
}