//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Trainee {
    public partial class Default {
        protected global::System.Web.UI.WebControls.Label lblTraineeName;
        protected global::System.Web.UI.WebControls.Label lblTraineeID;
        protected global::System.Web.UI.WebControls.Label lblTraineeType;
        protected global::System.Web.UI.WebControls.LinkButton lnkActiveTraining;
        protected global::System.Web.UI.WebControls.Label lblActiveTraining;
        protected global::System.Web.UI.WebControls.LinkButton lnkPreviousTraining;
        protected global::System.Web.UI.WebControls.Label lblPreviousTraining;
        protected global::System.Web.UI.WebControls.LinkButton lnkCompletedTraining;
        protected global::System.Web.UI.WebControls.Label lblCompletedTraining;
        protected global::System.Web.UI.WebControls.LinkButton lnkFutureTraining;
        protected global::System.Web.UI.WebControls.Label lblFutureTraining;
        protected global::System.Web.UI.WebControls.LinkButton lnkPendingTests;
        protected global::System.Web.UI.WebControls.Label lblPendingTests;
        protected global::System.Web.UI.WebControls.LinkButton lnkCertificate;
        protected global::System.Web.UI.WebControls.Label lblCertificate;
    }
}