<%@ Page Title="Trainee Dashboard" Language="C#" MasterPageFile="~/TraineeMaster.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Training.Trainee.Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<style type="text/css">
.trainee-dashboard{padding-bottom:25px}.welcome-card{border:0;border-radius:14px;background:linear-gradient(135deg,#0d6efd,#084298);color:#fff;box-shadow:0 5px 18px rgba(13,110,253,.18);margin-bottom:22px;overflow:hidden}.welcome-body{padding:22px 25px}.welcome-title{font-size:24px;font-weight:700;margin-bottom:5px}.welcome-subtitle{font-size:14px;opacity:.9}.trainee-name{font-weight:700}.trainee-id{display:inline-block;margin-top:10px;padding:5px 12px;background:rgba(255,255,255,.15);border-radius:20px;font-size:13px}.dashboard-section{margin-bottom:22px}.section-heading{font-size:18px;font-weight:700;color:#343a40;margin-bottom:14px}.section-heading i{margin-right:6px;color:#0d6efd}.summary-card{position:relative;background:#fff;border:1px solid #e8edf3;border-radius:12px;min-height:135px;padding:18px;margin-bottom:20px;box-shadow:0 3px 12px rgba(0,0,0,.06);overflow:hidden;transition:all .2s ease-in-out}.summary-card:hover{transform:translateY(-3px);box-shadow:0 7px 18px rgba(0,0,0,.1)}.summary-icon{width:48px;height:48px;border-radius:12px;text-align:center;line-height:48px;font-size:21px;margin-bottom:12px}.icon-training{background:#e7f1ff;color:#0d6efd}.icon-history{background:#fff3cd;color:#997404}.icon-completed{background:#e8f7ee;color:#198754}.icon-test{background:#fff3cd;color:#997404}.icon-certificate{background:#fff0e5;color:#fd7e14}.summary-value{font-size:27px;line-height:30px;font-weight:700;color:#212529}.summary-label{margin-top:4px;color:#6c757d;font-size:14px;font-weight:600}.summary-small{display:block;margin-top:5px;color:#8a929a;font-size:12px}.dashboard-link{display:block;color:inherit;text-decoration:none!important}.dashboard-link:hover,.dashboard-link:focus{color:inherit;text-decoration:none!important}@media(max-width:767px){.welcome-body{padding:18px}.welcome-title{font-size:20px}.summary-card{min-height:120px}.summary-value{font-size:24px}}
</style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="container-fluid trainee-dashboard">
<div class="welcome-card"><div class="welcome-body"><div class="welcome-title">Welcome, <asp:Label ID="lblTraineeName" runat="server" CssClass="trainee-name" Text="Trainee"></asp:Label></div><div class="welcome-subtitle">View your assigned trainings, tests and certificates from your dashboard.</div><div class="trainee-id">Trainee ID : <asp:Label ID="lblTraineeID" runat="server"></asp:Label> &nbsp; | &nbsp; <asp:Label ID="lblTraineeType" runat="server"></asp:Label></div></div></div>
<div class="dashboard-section"><div class="section-heading"><i class="fa fa-bar-chart"></i> Training Summary</div><div class="row">
<div class="col-lg-3 col-md-6 col-sm-6"><asp:LinkButton ID="lnkActiveTraining" runat="server" CssClass="dashboard-link" CausesValidation="false" OnClick="lnkActiveTraining_Click"><div class="summary-card"><div class="summary-icon icon-training"><i class="fa fa-play-circle"></i></div><div class="summary-value"><asp:Label ID="lblActiveTraining" runat="server" Text="0"></asp:Label></div><div class="summary-label">Active Training</div><span class="summary-small">Training currently running</span></div></asp:LinkButton></div>
<div class="col-lg-3 col-md-6 col-sm-6"><asp:LinkButton ID="lnkPreviousTraining" runat="server" CssClass="dashboard-link" CausesValidation="false" OnClick="lnkPreviousTraining_Click"><div class="summary-card"><div class="summary-icon icon-history"><i class="fa fa-history"></i></div><div class="summary-value"><asp:Label ID="lblPreviousTraining" runat="server" Text="0"></asp:Label></div><div class="summary-label">Previous Training</div><span class="summary-small">Previous training not yet closed</span></div></asp:LinkButton></div>
<div class="col-lg-3 col-md-6 col-sm-6"><asp:LinkButton ID="lnkCompletedTraining" runat="server" CssClass="dashboard-link" CausesValidation="false" OnClick="lnkCompletedTraining_Click"><div class="summary-card"><div class="summary-icon icon-completed"><i class="fa fa-check-square-o"></i></div><div class="summary-value"><asp:Label ID="lblCompletedTraining" runat="server" Text="0"></asp:Label></div><div class="summary-label">Completed Training</div><span class="summary-small">Training already closed</span></div></asp:LinkButton></div>
<div class="col-lg-3 col-md-6 col-sm-6"><asp:LinkButton ID="lnkFutureTraining" runat="server" CssClass="dashboard-link" CausesValidation="false" OnClick="lnkFutureTraining_Click"><div class="summary-card"><div class="summary-icon icon-training"><i class="fa fa-calendar"></i></div><div class="summary-value"><asp:Label ID="lblFutureTraining" runat="server" Text="0"></asp:Label></div><div class="summary-label">Future Assigned Training</div><span class="summary-small">Training scheduled for a future date</span></div></asp:LinkButton></div>
<div class="col-lg-3 col-md-6 col-sm-6"><asp:LinkButton ID="lnkPendingTests" runat="server" CssClass="dashboard-link" CausesValidation="false" OnClick="lnkPendingTests_Click"><div class="summary-card"><div class="summary-icon icon-test"><i class="fa fa-clock-o"></i></div><div class="summary-value"><asp:Label ID="lblPendingTests" runat="server" Text="0"></asp:Label></div><div class="summary-label">Pending Tests</div><span class="summary-small">Published tests awaiting completion</span></div></asp:LinkButton></div>
<div class="col-lg-3 col-md-6 col-sm-6"><asp:LinkButton ID="lnkCertificate" runat="server" CssClass="dashboard-link" CausesValidation="false" OnClick="lnkCertificate_Click"><div class="summary-card"><div class="summary-icon icon-certificate"><i class="fa fa-certificate"></i></div><div class="summary-value"><asp:Label ID="lblCertificate" runat="server" Text="0"></asp:Label></div><div class="summary-label">Certificates</div><span class="summary-small">Certificates available for download</span></div></asp:LinkButton></div>
</div></div>
</div>
</asp:Content>
