//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    public partial class BatchLifecycle
    {
        /// <summary>
        /// pnlLifecycle control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlLifecycle;

        /// <summary>
        /// litLifecycle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litLifecycle;
    }
}