//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Training
{
    public partial class SuperAdminMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.HyperLink lnkCreateUser;
        protected global::System.Web.UI.WebControls.HyperLink lnkUserManagement;
        protected global::System.Web.UI.WebControls.HyperLink lnkPasswordManagement;
        protected global::System.Web.UI.WebControls.HyperLink lnkLoginHistory;
        protected global::System.Web.UI.WebControls.HyperLink lnkActivityLog;
        protected global::System.Web.UI.WebControls.HyperLink lnkLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
    }
}