//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training
{
    public partial class TrainingHistory
    {
        protected global::System.Web.UI.WebControls.Label lblTrainingID;
        protected global::System.Web.UI.WebControls.Label lblTrainingType;
        protected global::System.Web.UI.WebControls.Label lblOrganizer;
        protected global::System.Web.UI.WebControls.Label lblBatch;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblDateFrom;
        protected global::System.Web.UI.WebControls.Label lblDateTo;
        protected global::System.Web.UI.WebControls.Button btnCertificate;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.GridView gvAttendance;
        protected global::System.Web.UI.WebControls.GridView gvTests;
        protected global::System.Web.UI.WebControls.GridView gvQuestions;
        protected global::System.Web.UI.WebControls.GridView gvFeedback;
    }
}
