//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace Training.Trainer {
    public partial class SessionDetails {
        protected global::Training.Trainer.TrainerSummary TrainerSummary1;
        protected global::Training.Trainer.SessionSummary SessionSummary1;
        protected global::System.Web.UI.WebControls.Button btnDashboard;
        protected global::System.Web.UI.WebControls.Button btnAttendance;
        protected global::System.Web.UI.WebControls.Button btnMaterial;
        protected global::System.Web.UI.WebControls.Button btnQuestionBank;
        protected global::System.Web.UI.WebControls.Button btnPreTest;
        protected global::System.Web.UI.WebControls.Button btnPostTest;
        protected global::System.Web.UI.WebControls.Panel pnlSkip;
        protected global::System.Web.UI.WebControls.Label lblAttendanceSkip;
        protected global::System.Web.UI.WebControls.TextBox txtAttendanceSkipReason;
        protected global::System.Web.UI.WebControls.Button btnSkipAttendance;
        protected global::System.Web.UI.WebControls.Label lblPreSkip;
        protected global::System.Web.UI.WebControls.TextBox txtPreSkipReason;
        protected global::System.Web.UI.WebControls.Button btnSkipPre;
        protected global::System.Web.UI.WebControls.Label lblPostSkip;
        protected global::System.Web.UI.WebControls.TextBox txtPostSkipReason;
        protected global::System.Web.UI.WebControls.Button btnSkipPost;
        protected global::System.Web.UI.WebControls.Label lblSkipMessage;
        protected global::System.Web.UI.WebControls.Label lblWorkflow;
        protected global::System.Web.UI.WebControls.Label lblTrainingStatus;
        protected global::System.Web.UI.WebControls.Label lblAttendanceStatus;
        protected global::System.Web.UI.WebControls.Label lblSessionStatus;
    }
}