<%@ Page Title="Finance - Training Costing" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="FinanceCosting.aspx.cs" Inherits="Training.Admin.FinanceCosting" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<style>
body{background:#f5f5f5}.main-card{background:#fff;padding:25px;border-radius:12px;box-shadow:0 0 10px #d9d9d9;margin:20px 0}.page-heading{font-size:28px;font-weight:bold;color:darkcyan;margin-bottom:4px}.page-subheading{color:#6c757d;display:block;margin-bottom:22px}.finance-section{border-top:1px solid #e5e5e5;padding-top:20px;margin-top:20px}.finance-section-title{font-size:20px;font-weight:bold;color:darkcyan;margin-bottom:18px}.form-label{font-weight:500;margin-bottom:6px;color:#343a40}.form-control,.form-select{height:38px;border:1px solid #ced4da;border-radius:4px}.btn-save{background:darkcyan;color:#fff;border:none}.btn-save:hover{background:teal;color:#fff}.finance-table{margin-bottom:0!important}.finance-table th{background:darkcyan!important;color:#fff!important;white-space:nowrap;font-weight:600;padding:10px 12px}.finance-table td{vertical-align:middle;padding:9px 12px}.finance-table tbody tr:hover{background:#f8fbfb}.table-wrap{overflow-x:auto;border:1px solid #dee2e6;border-radius:6px}.message{display:block;margin-bottom:10px}.total-box{height:38px;display:flex;align-items:center;font-size:19px;font-weight:bold;color:darkcyan;background:#f8f9fa;border:1px solid #ced4da;border-radius:4px;padding:0 12px}@media(max-width:767px){.main-card{padding:18px}.page-heading{font-size:24px}}
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="container-fluid"><div class="main-card">
<div class="page-heading">Finance - Training Costing</div><span class="page-subheading">Calculate and review batch-wise training cost</span>
<asp:Label ID="lblMessage" runat="server" CssClass="font-weight-bold message"></asp:Label>
<div class="row">
<div class="col-lg-5 col-md-12 mb-3"><label class="form-label">Training / Batch</label><asp:DropDownList ID="ddlTraining" runat="server" CssClass="form-select" AutoPostBack="true" OnSelectedIndexChanged="ddlTraining_SelectedIndexChanged"></asp:DropDownList></div>
<div class="col-lg-2 col-md-4 col-6 mb-3"><label class="form-label">Trainees</label><asp:Label ID="lblTrainees" runat="server" CssClass="form-control bg-light"></asp:Label></div>
<div class="col-lg-2 col-md-4 col-6 mb-3"><label class="form-label">Training Days</label><asp:Label ID="lblDays" runat="server" CssClass="form-control bg-light"></asp:Label></div>
<div class="col-lg-3 col-md-4 mb-3"><label class="form-label">Total Cost</label><div class="total-box"><asp:Label ID="lblTotal" runat="server" Text="₹0.00"></asp:Label></div></div>
</div>
<div class="finance-section"><div class="finance-section-title"><i class="fas fa-file-invoice-dollar mr-2"></i>Batch Costing Details</div>
<div class="table-wrap"><asp:GridView ID="gvCosting" runat="server" CssClass="table table-bordered table-hover mb-0 finance-table" AutoGenerateColumns="False" DataKeyNames="CostingDetailID" OnRowCommand="gvCosting_RowCommand">
<Columns><asp:BoundField DataField="CostHeadName" HeaderText="Cost Head" /><asp:BoundField DataField="CostLevel" HeaderText="Level" /><asp:BoundField DataField="CalculationMode" HeaderText="Mode" /><asp:BoundField DataField="UnitType" HeaderText="Unit" /><asp:BoundField DataField="Quantity" HeaderText="Qty" DataFormatString="{0:N2}" /><asp:BoundField DataField="AppliedRate" HeaderText="Rate" DataFormatString="{0:N2}" /><asp:BoundField DataField="CalculatedAmount" HeaderText="Calculated" DataFormatString="{0:N2}" /><asp:BoundField DataField="FinalAmount" HeaderText="Final" DataFormatString="{0:N2}" /><asp:BoundField DataField="OverrideAmount" HeaderText="Override" DataFormatString="{0:N2}" /><asp:TemplateField HeaderText="Manual Override"><ItemTemplate><asp:TextBox ID="txtOverride" runat="server" CssClass="form-control form-control-sm" Text='<%# Eval("OverrideAmount") %>'></asp:TextBox><asp:Button ID="btnOverride" runat="server" Text="Save" CssClass="btn btn-sm btn-primary mt-1" CommandName="SaveOverride" CommandArgument="<%# Container.DataItemIndex %>" /></ItemTemplate></asp:TemplateField></Columns>
</asp:GridView></div></div>
<div class="finance-section"><div class="finance-section-title"><i class="fas fa-chart-pie mr-2"></i>Course-wise Summary</div>
<div class="table-wrap"><asp:GridView ID="gvCourse" runat="server" CssClass="table table-bordered table-hover mb-0 finance-table" AutoGenerateColumns="False"><Columns><asp:BoundField DataField="CourseName" HeaderText="Course" /><asp:BoundField DataField="BatchCount" HeaderText="Batches" /><asp:BoundField DataField="CourseCost" HeaderText="Course Cost" DataFormatString="{0:N2}" /><asp:BoundField DataField="AverageBatchCost" HeaderText="Avg Batch Cost" DataFormatString="{0:N2}" /></Columns></asp:GridView></div></div>
</div></div></asp:Content>