<%@ Page Title="Trainee Answer Details" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="AnswerDetails.aspx.cs" Inherits="Training.Admin.AnswerDetails" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style type="text/css">
.page-heading{font-size:24px;font-weight:700;color:#0d6efd;margin-bottom:20px}.detail-card{background:#fff;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,.08);margin-bottom:20px;overflow:hidden}.card-title-bar{padding:12px 18px;font-size:17px;font-weight:600;color:#fff}.info-box{background:#f8f9fa;border:1px solid #e9ecef;border-radius:8px;padding:12px 15px;margin-bottom:15px;height:100%}.info-label{display:block;font-size:12px;font-weight:600;color:#6c757d;text-transform:uppercase;margin-bottom:4px}.info-value{font-size:16px;font-weight:600;color:#212529}.question-grid th{background:#0d6efd;color:#fff;text-align:center;vertical-align:middle;white-space:nowrap}.question-grid td{vertical-align:top}.question-text{font-weight:600;line-height:1.45}.option-list{min-width:280px}.option-item{padding:7px 10px;margin:3px 0;border-radius:5px;border:1px solid #e9ecef}.option-selected{font-weight:600}.option-correct{background:#d1e7dd;border-color:#a3cfbb}.option-wrong{background:#f8d7da;border-color:#f1aeb5}.option-answer{background:#cfe2ff;border-color:#9ec5fe}.badge-soft{font-size:12px;padding:5px 8px}.btn-back{min-width:150px}.result-pass{color:#198754;font-weight:700}.result-fail{color:#dc3545;font-weight:700}
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container-fluid">
<div class="page-heading">Trainee Answer Details</div>
<div class="detail-card"><div class="card-title-bar bg-primary">Trainee &amp; Examination Information</div><div class="p-3">
<div class="row"><div class="col-md-3"><div class="info-box"><span class="info-label">Employee ID</span><asp:Label ID="lblEmpID" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Employee Name</span><asp:Label ID="lblEmpName" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Designation</span><asp:Label ID="lblDesignation" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Result</span><asp:Label ID="lblStatus" runat="server" CssClass="info-value" /></div></div></div>
<div class="row"><div class="col-md-3"><div class="info-box"><span class="info-label">Test ID</span><asp:Label ID="lblTestID" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Exam</span><asp:Label ID="lblTestType" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Attempt</span><asp:Label ID="lblAttempt" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Submitted On</span><asp:Label ID="lblSubmittedOn" runat="server" CssClass="info-value" /></div></div></div>
<div class="row"><div class="col-md-3"><div class="info-box"><span class="info-label">Total Questions</span><asp:Label ID="lblTotalQ" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Attempted</span><asp:Label ID="lblAttempted" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Correct Answers</span><asp:Label ID="lblCorrect" runat="server" CssClass="info-value" /></div></div><div class="col-md-3"><div class="info-box"><span class="info-label">Score</span><asp:Label ID="lblScore" runat="server" CssClass="info-value" /></div></div></div>
</div></div>
<div class="detail-card"><div class="card-title-bar bg-success">Question-wise Answer Review</div><div class="p-3"><div class="table-responsive">
<asp:GridView ID="gvAnswers" runat="server" AutoGenerateColumns="False" CssClass="table table-bordered table-hover question-grid" EmptyDataText="No Answers Found" ShowHeaderWhenEmpty="true"><Columns>
<asp:TemplateField HeaderText="#"><ItemTemplate><%# Container.DataItemIndex + 1 %></ItemTemplate><ItemStyle Width="50px" HorizontalAlign="Center" /></asp:TemplateField>
<asp:TemplateField HeaderText="Question"><ItemTemplate><div class="question-text"><%# Eval("Question") %></div></ItemTemplate></asp:TemplateField>
<asp:BoundField DataField="Type" HeaderText="Type" />
<asp:TemplateField HeaderText="Options"><ItemTemplate><%# GetOptions(Eval("OptionA"), Eval("OptionB"), Eval("OptionC"), Eval("OptionD"), Eval("SelectedAnswer"), Eval("CorrectAnswer")) %></ItemTemplate></asp:TemplateField>
<asp:TemplateField HeaderText="Selected"><ItemTemplate><span class='<%# IsCorrect(Eval("IsCorrect")) ? "badge bg-success badge-soft" : "badge bg-danger badge-soft" %>'><%# String.IsNullOrWhiteSpace(Eval("SelectedAnswer").ToString()) ? "Not Answered" : Eval("SelectedAnswer") %></span></ItemTemplate><ItemStyle HorizontalAlign="Center" /></asp:TemplateField>
<asp:TemplateField HeaderText="Correct"><ItemTemplate><span class="badge bg-primary badge-soft"><%# Eval("CorrectAnswer") %></span></ItemTemplate><ItemStyle HorizontalAlign="Center" /></asp:TemplateField>
<asp:TemplateField HeaderText="Result"><ItemTemplate><span class='<%# IsCorrect(Eval("IsCorrect")) ? "badge bg-success badge-soft" : "badge bg-danger badge-soft" %>'><%# IsCorrect(Eval("IsCorrect")) ? "Correct" : "Wrong" %></span></ItemTemplate><ItemStyle HorizontalAlign="Center" /></asp:TemplateField>
</Columns></asp:GridView>
</div></div></div>
<div class="text-center mb-4"><asp:Button ID="btnBack" runat="server" Text="Back to Exam Results" CssClass="btn btn-secondary btn-lg btn-back" OnClick="btnBack_Click" /></div>
</div></asp:Content>
