//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Admin {
    
    public partial class CertificatePreview {
        
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCertificate;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Label lblHeader;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divBody;
        protected global::System.Web.UI.WebControls.Label lblEmployee;
        protected global::System.Web.UI.WebControls.Label lblCourse;
        protected global::System.Web.UI.WebControls.Label lblDuration;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divLeftSignature;
        protected global::System.Web.UI.WebControls.Image imgLeftSignature;
        protected global::System.Web.UI.WebControls.Label lblLeftName;
        protected global::System.Web.UI.WebControls.Label lblLeftDesignation;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRightSignature;
        protected global::System.Web.UI.WebControls.Image imgRightSignature;
        protected global::System.Web.UI.WebControls.Label lblRightName;
        protected global::System.Web.UI.WebControls.Label lblRightDesignation;
        protected global::System.Web.UI.WebControls.Label lblFooter;
    }
}
