//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Admin
{
    public partial class CloneTest
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlSourceTest;
        protected global::System.Web.UI.WebControls.Panel pnlSourceDetails;
        protected global::System.Web.UI.WebControls.Label lblSrcType;
        protected global::System.Web.UI.WebControls.Label lblSrcDuration;
        protected global::System.Web.UI.WebControls.Label lblSrcTotalQuestions;
        protected global::System.Web.UI.WebControls.Label lblSrcTotalMarks;
        protected global::System.Web.UI.WebControls.DropDownList ddlTargetTraining;
        protected global::System.Web.UI.WebControls.DropDownList ddlTargetSession;
        protected global::System.Web.UI.WebControls.Button btnClone;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}