//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Admin
{
    public partial class ExamResultReport
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlTrainingList;
        protected global::System.Web.UI.WebControls.Button btnExportTraining;
        protected global::System.Web.UI.WebControls.DropDownList ddlCourseFilter;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.TextBox txtTrainingSearch;
        protected global::System.Web.UI.WebControls.Button btnSearchTraining;
        protected global::System.Web.UI.WebControls.Button btnResetTraining;
        protected global::System.Web.UI.WebControls.Label lblTrainingCount;
        protected global::System.Web.UI.WebControls.GridView gvTrainingList;
        protected global::System.Web.UI.WebControls.Panel pnlSessionList;
        protected global::System.Web.UI.WebControls.LinkButton btnBackTraining;
        protected global::System.Web.UI.WebControls.Label lblSelectedTraining;
        protected global::System.Web.UI.WebControls.Button btnExportSessions;
        protected global::System.Web.UI.WebControls.GridView gvSessionList;
        protected global::System.Web.UI.WebControls.Panel pnlResultList;
        protected global::System.Web.UI.WebControls.LinkButton btnBackSessions;
        protected global::System.Web.UI.WebControls.Label lblSelectedSession;
        protected global::System.Web.UI.WebControls.Label lblResultCount;
        protected global::System.Web.UI.WebControls.Label lblPassed;
        protected global::System.Web.UI.WebControls.Label lblFailed;
        protected global::System.Web.UI.WebControls.Label lblAveragePercentage;
        protected global::System.Web.UI.WebControls.Button btnExportResults;
        protected global::System.Web.UI.WebControls.GridView gvResultList;
    }
}