//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace Training.Admin {
    public partial class ManageTraining {
        protected global::Training.Admin.TrainingSummary TrainingSummary1;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Button btnUpdateTraining;
        protected global::System.Web.UI.WebControls.Button btnAssignSession;
        protected global::System.Web.UI.WebControls.Button btnAssignTrainee;
        protected global::System.Web.UI.WebControls.Button btnRequirements;
        protected global::System.Web.UI.WebControls.Button btnCertificateRules;
        protected global::System.Web.UI.WebControls.Button btnAssignFeedback;
        protected global::System.Web.UI.WebControls.Button btnCertificateTemplate;
        protected global::System.Web.UI.WebControls.Button btnAssignHostel;
        protected global::System.Web.UI.WebControls.Button btnStartTraining;
        protected global::System.Web.UI.WebControls.Button btnAttendance;
        
        protected global::System.Web.UI.WebControls.Button btnCloseTraining;
        protected global::System.Web.UI.WebControls.Panel pnlHostelConfirmation;
        protected global::System.Web.UI.WebControls.Button btnHostelYes;
        protected global::System.Web.UI.WebControls.Button btnHostelNo;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Literal litBatchLifecycle;
    }
}