//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace Training.Admin {
    public partial class SetCertificateRules {
        protected global::System.Web.UI.WebControls.Label lblTraining;
        protected global::System.Web.UI.WebControls.TextBox txtMinimumAttendance;
        protected global::System.Web.UI.WebControls.Button btnSaveAttendance;
        protected global::System.Web.UI.WebControls.Label lblAttendanceStatus;
        protected global::System.Web.UI.WebControls.GridView gvSessions;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}