<%@ Page Title="Training Report" Language="C#" MasterPageFile="~/AdminMaster.Master" AutoEventWireup="true" CodeBehind="TrainingDetailsReport.aspx.cs" Inherits="Training.Admin.TrainingDetailsReport" EnableEventValidation="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" />
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<style>
*{box-sizing:border-box}html,body{width:100%;max-width:100%;margin:0;padding:0}body{overflow-x:hidden}

.report-wrap{padding:22px;background:#f5f7fb}.report-card{background:#fff;border-radius:14px;box-shadow:0 3px 14px rgba(15,23,42,.08);padding:22px;margin-bottom:20px}.report-title{font-size:25px;font-weight:700;color:#17365d;margin-bottom:18px}.filter-grid{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));gap:14px}.report-wrap .field label{display:block;font-weight:600;color:#334155;margin-bottom:6px}.report-wrap .input{width:100%;padding:9px 11px;border:1px solid #cbd5e1;border-radius:7px;box-sizing:border-box}.report-wrap .actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.btnx{border:0;border-radius:7px;padding:9px 16px;font-weight:600;cursor:pointer}.blue{background:#2563eb;color:#fff}.gray{background:#64748b;color:#fff}.green{background:#198754;color:#fff}.orange{background:#f59e0b;color:#fff}.purple{background:#7c3aed;color:#fff}.teal{background:#0f766e;color:#fff}.red{background:#dc2626;color:#fff}.grid-wrap{overflow:auto}.grid{width:100%;min-width:1050px;border-collapse:collapse}.grid th{background:#17365d;color:#fff;padding:10px;text-align:left;white-space:nowrap}.training-link{color:#2563eb;font-weight:700;text-decoration:none}.training-popup{position:fixed;inset:0;display:none;align-items:center;justify-content:center;background:rgba(15,23,42,.55);z-index:99999;padding:20px}.training-popup-box{width:100%;max-width:560px;background:#fff;border-radius:12px;box-shadow:0 15px 45px rgba(0,0,0,.25);overflow:hidden}.training-popup-header{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;background:#17365d;color:#fff}.training-popup-title{font-size:18px;font-weight:700}.training-popup-close{border:0;background:transparent;color:#fff;font-size:24px;line-height:1;cursor:pointer}.training-popup-body{padding:18px}.info-table{width:100%;border-collapse:collapse}.info-table th{background:#f8fafc;width:35%;padding:10px;text-align:left;border-bottom:1px solid #e2e8f0}.info-table td{padding:10px;border-bottom:1px solid #e2e8f0}.training-link{color:#2563eb;font-weight:700;text-decoration:none}.grid td{padding:9px;border:1px solid #e2e8f0;white-space:nowrap}.grid tr:nth-child(even){background:#f8fafc}.detail-head{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.training-info{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.info{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:10px}.info b{display:block;color:#64748b;font-size:12px}.info span{font-weight:600;color:#1e293b}.report-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:15px 0}.session-action{min-width:85px}.report-wrap .message{font-weight:600;color:#475569;margin:10px 0}@media(max-width:1000px){.filter-grid{grid-template-columns:repeat(2,1fr)}.training-info{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.filter-grid,.training-info{grid-template-columns:1fr}.report-wrap{padding:10px}.report-card{padding:14px}}

        form > hr + .container-fluid.text-white.py-4{width:100%!important;max-width:100%!important;min-width:0!important;box-sizing:border-box!important;clear:both!important;overflow:hidden!important;margin-left:0!important;margin-right:0!important}
        form > hr + .container-fluid.text-white.py-4 .text-center{width:100%!important;max-width:100%!important;box-sizing:border-box!important;text-align:center!important}
        form > hr + .container-fluid.text-white.py-4 img{max-width:100%!important;height:auto!important;vertical-align:middle!important}
</style>
<script>document.addEventListener("DOMContentLoaded",function(){flatpickr(".datepicker",{dateFormat:"d-m-Y",allowInput:true});});</script>
</asp:Content>