//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace Training.Manager
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Label lblManagerID;
        protected global::System.Web.UI.WebControls.Label lblEmpID;
        protected global::System.Web.UI.WebControls.Label lblName;
        protected global::System.Web.UI.WebControls.Label lblDesignation;
        protected global::System.Web.UI.WebControls.Label lblPosting;
        protected global::System.Web.UI.WebControls.Label lblMapForLocation;
        protected global::System.Web.UI.WebControls.Label lblTrainingLocation;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.GridView gvTraining;
        protected global::System.Web.UI.WebControls.GridView gvSession;
    }
}