<%@ Page Title="Training Requirements" Language="C#" MasterPageFile="~/ManagerMaster.Master" AutoEventWireup="true" CodeBehind="TrainingRequirements.aspx.cs" Inherits="Training.Manager.TrainingRequirements" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
<style>
.main-card{background:#fff;padding:25px;border-radius:12px;box-shadow:0 0 10px #d9d9d9;margin-top:20px}.heading{font-size:26px;font-weight:700;margin-bottom:20px}.req-card{border:1px solid #dee2e6;border-radius:10px;padding:18px;margin-bottom:20px}.req-box{border:1px solid #e5e5e5;border-radius:8px;padding:15px;height:100%}.req-status{display:inline-block;margin:6px 0 10px}.reason{max-width:500px}.table td,.table th{vertical-align:middle}.action-btn{margin:2px 4px 2px 0}
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<div class="container-fluid"><div class="main-card">
<div class="heading">Training Requirements</div>
<asp:Label ID="lblTraining" runat="server" CssClass="fw-bold" />

<div class="req-card mt-3"><h5>Batch-wise Requirements</h5><p class="text-muted">Admin can change any requirement from Required to Not Required or from Not Required to Required after the batch is created.</p>
<div class="row g-3">
<div class="col-md-6 col-lg-4"><div class="req-box"><b>Attendance</b><br /><asp:Label ID="lblAttendanceStatus" runat="server" CssClass="badge bg-secondary req-status" /><br /><asp:Button ID="btnAttendanceRequired" runat="server" Text="Make Required" CssClass="btn btn-sm btn-outline-success action-btn" OnClick="btnAttendanceRequired_Click" /><asp:Button ID="btnAttendanceNotRequired" runat="server" Text="Make Not Required" CssClass="btn btn-sm btn-outline-secondary action-btn" OnClick="btnAttendanceNotRequired_Click" /></div></div>
<div class="col-md-6 col-lg-4"><div class="req-box"><b>Pre-Test</b><br /><asp:Label ID="lblPreStatus" runat="server" CssClass="badge bg-secondary req-status" /><br /><asp:Button ID="btnPreRequired" runat="server" Text="Make Required" CssClass="btn btn-sm btn-outline-success action-btn" OnClick="btnPreRequired_Click" /><asp:Button ID="btnPreNotRequired" runat="server" Text="Make Not Required" CssClass="btn btn-sm btn-outline-secondary action-btn" OnClick="btnPreNotRequired_Click" /></div></div>
<div class="col-md-6 col-lg-4"><div class="req-box"><b>Post-Test</b><br /><asp:Label ID="lblPostStatus" runat="server" CssClass="badge bg-secondary req-status" /><br /><asp:Button ID="btnPostRequired" runat="server" Text="Make Required" CssClass="btn btn-sm btn-outline-success action-btn" OnClick="btnPostRequired_Click" /><asp:Button ID="btnPostNotRequired" runat="server" Text="Make Not Required" CssClass="btn btn-sm btn-outline-secondary action-btn" OnClick="btnPostNotRequired_Click" /></div></div>
<div class="col-md-6 col-lg-6"><div class="req-box"><b>Feedback</b><br /><asp:Label ID="lblFeedbackStatus" runat="server" CssClass="badge bg-secondary req-status" /><br /><asp:Button ID="btnFeedbackRequired" runat="server" Text="Make Required" CssClass="btn btn-sm btn-outline-success action-btn" OnClick="btnFeedbackRequired_Click" /><asp:Button ID="btnFeedbackNotRequired" runat="server" Text="Make Not Required" CssClass="btn btn-sm btn-outline-secondary action-btn" OnClick="btnFeedbackNotRequired_Click" /><asp:TextBox ID="txtFeedbackReason" runat="server" TextMode="MultiLine" Rows="2" CssClass="form-control reason mt-2" placeholder="Reason required when skipping Feedback" /><asp:Button ID="btnFeedback" runat="server" CssClass="btn btn-outline-danger mt-2 action-btn" OnClick="btnFeedback_Click" /></div></div>
<div class="col-md-6 col-lg-6"><div class="req-box"><b>Certificate</b><br /><asp:Label ID="lblCertificateStatus" runat="server" CssClass="badge bg-secondary req-status" /><br /><asp:Button ID="btnCertificateRequired" runat="server" Text="Make Required" CssClass="btn btn-sm btn-outline-success action-btn" OnClick="btnCertificateRequired_Click" /><asp:Button ID="btnCertificateNotRequired" runat="server" Text="Make Not Required" CssClass="btn btn-sm btn-outline-secondary action-btn" OnClick="btnCertificateNotRequired_Click" /><br /><asp:Label ID="lblCertificateBasis" runat="server" CssClass="fw-bold" /><br />
<asp:Panel ID="pnlPreCertificateRule" runat="server" CssClass="mt-2">
<b>Pre-Test Certificate Rule</b><br />
<asp:DropDownList ID="ddlPreCertificateRule" runat="server" CssClass="form-select mt-1"><asp:ListItem Value="">Select Rule</asp:ListItem><asp:ListItem Value="ALL">Certificate to All (Pass or Fail)</asp:ListItem><asp:ListItem Value="PASS">Certificate to Pass Only</asp:ListItem></asp:DropDownList>
<asp:Button ID="btnSavePreCertificateRule" runat="server" Text="Save Pre-Test Rule" CssClass="btn btn-sm btn-outline-primary mt-1 action-btn" OnClick="btnSavePreCertificateRule_Click" />
</asp:Panel>
<asp:Panel ID="pnlPostCertificateRule" runat="server" CssClass="mt-2">
<b>Post-Test Certificate Rule</b><br />
<asp:DropDownList ID="ddlPostCertificateRule" runat="server" CssClass="form-select mt-1"><asp:ListItem Value="">Select Rule</asp:ListItem><asp:ListItem Value="ALL">Certificate to All (Pass or Fail)</asp:ListItem><asp:ListItem Value="PASS">Certificate to Pass Only</asp:ListItem></asp:DropDownList>
<asp:Button ID="btnSavePostCertificateRule" runat="server" Text="Save Post-Test Rule" CssClass="btn btn-sm btn-outline-primary mt-1 action-btn" OnClick="btnSavePostCertificateRule_Click" />
</asp:Panel><asp:TextBox ID="txtCertificateReason" runat="server" TextMode="MultiLine" Rows="2" CssClass="form-control reason mt-2" placeholder="Reason required when skipping Certificate" /><asp:Button ID="btnCertificate" runat="server" CssClass="btn btn-outline-danger mt-2 action-btn" OnClick="btnCertificate_Click" /></div></div>
</div></div>

<div class="req-card"><h5>Session-wise Skip / Unskip</h5><p class="text-muted">Trainer/Admin can skip a session requirement. Admin can always unskip it again. Skipped sessions do not block the workflow.</p>
<asp:GridView ID="gvSessions" runat="server" AutoGenerateColumns="False" CssClass="table table-bordered table-striped" DataKeyNames="SessionID" OnRowCommand="gvSessions_RowCommand"><Columns>
<asp:BoundField DataField="SessionID" HeaderText="Session" />
<asp:TemplateField HeaderText="Attendance"><ItemTemplate><asp:Label runat="server" Text='<%# Convert.ToBoolean(Eval("AttendanceSkipped")) ? "Skipped" : (Convert.ToBoolean(Eval("AttendanceRequired")) ? "Required" : "Not Required") %>' CssClass='<%# Convert.ToBoolean(Eval("AttendanceSkipped")) ? "badge bg-secondary" : (Convert.ToBoolean(Eval("AttendanceRequired")) ? "badge bg-success" : "badge bg-light text-dark") %>' /><br /><asp:TextBox ID="txtAttendanceReason" runat="server" CssClass="form-control mt-1" placeholder="Skip reason" /><asp:Button ID="btnAttendanceReq" runat="server" Text='<%# Convert.ToBoolean(Eval("AttendanceSkipped")) ? "Unskip" : "Skip" %>' CommandName="Attendance" CommandArgument='<%# Eval("SessionID") %>' CssClass="btn btn-sm btn-outline-danger mt-1" /></ItemTemplate></asp:TemplateField>
<asp:TemplateField HeaderText="Pre-Test"><ItemTemplate><asp:Label runat="server" Text='<%# Convert.ToBoolean(Eval("PreAssessmentSkipped")) ? "Skipped" : (Convert.ToBoolean(Eval("InitialAssessmentRequired")) ? "Required" : "Not Required") %>' CssClass='<%# Convert.ToBoolean(Eval("PreAssessmentSkipped")) ? "badge bg-secondary" : (Convert.ToBoolean(Eval("InitialAssessmentRequired")) ? "badge bg-success" : "badge bg-light text-dark") %>' /><br /><asp:TextBox ID="txtPreReason" runat="server" CssClass="form-control mt-1" placeholder="Skip reason" /><asp:Button ID="btnPreReq" runat="server" Text='<%# Convert.ToBoolean(Eval("PreAssessmentSkipped")) ? "Unskip" : "Skip" %>' CommandName="Pre" CommandArgument='<%# Eval("SessionID") %>' CssClass="btn btn-sm btn-outline-danger mt-1" /></ItemTemplate></asp:TemplateField>
<asp:TemplateField HeaderText="Post-Test"><ItemTemplate><asp:Label runat="server" Text='<%# Convert.ToBoolean(Eval("PostAssessmentSkipped")) ? "Skipped" : (Convert.ToBoolean(Eval("FinalAssessmentRequired")) ? "Required" : "Not Required") %>' CssClass='<%# Convert.ToBoolean(Eval("PostAssessmentSkipped")) ? "badge bg-secondary" : (Convert.ToBoolean(Eval("FinalAssessmentRequired")) ? "badge bg-success" : "badge bg-light text-dark") %>' /><br /><asp:TextBox ID="txtPostReason" runat="server" CssClass="form-control mt-1" placeholder="Skip reason" /><asp:Button ID="btnPostReq" runat="server" Text='<%# Convert.ToBoolean(Eval("PostAssessmentSkipped")) ? "Unskip" : "Skip" %>' CommandName="Post" CommandArgument='<%# Eval("SessionID") %>' CssClass="btn btn-sm btn-outline-danger mt-1" /></ItemTemplate></asp:TemplateField>
</Columns></asp:GridView></div>
<asp:Label ID="lblMessage" runat="server" Font-Bold="true" />
</div></div>
</asp:Content>